spring.application.name=api
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
aws.regioin=us-east-2
aws.bucket.name=app-images
spring.kafka.bootstrap-servers=localhost:9092
api.security.token.secret=${JWT_SECRET:my-secret-key}
